import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { characterAsset } from "../src/character-spec.mjs";
import { visiblePngBounds } from "./png_alpha_bounds.mjs";

const scriptsDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = dirname(scriptsDirectory);

export async function collectCharacterVisualMetrics(
  assetsDirectory = join(projectRoot, "assets", "characters")
) {
  const metrics = {};

  for (let number = 1; number <= 150; number += 1) {
    const png = await readFile(join(assetsDirectory, characterAsset(number)));
    const pngWidth = png.readUInt32BE(16);
    const pngHeight = png.readUInt32BE(20);
    const bounds = visiblePngBounds(png);
    metrics[number] = {
      area: bounds.opaquePixels / (pngWidth * pngHeight),
      width: bounds.width / pngWidth,
      height: bounds.height / pngHeight
    };
  }

  return metrics;
}

export function characterVisualMetricsModule(metrics) {
  const referenceArea = Math.max(
    ...Array.from({ length: 10 }, (_, index) => metrics[index + 1].area)
  );
  return [
    "// Generated by scripts/generate_character_visual_metrics.mjs.",
    "// Do not edit by hand.",
    `export const CHARACTER_VISUAL_METRICS = Object.freeze(${JSON.stringify(metrics, null, 2)});`,
    `export const REFERENCE_VISUAL_AREA = ${JSON.stringify(referenceArea)};`,
    ""
  ].join("\n");
}

export async function writeCharacterVisualMetrics() {
  const metrics = await collectCharacterVisualMetrics();
  await writeFile(
    join(projectRoot, "src", "character-visual-metrics.mjs"),
    characterVisualMetricsModule(metrics),
    "utf8"
  );
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await writeCharacterVisualMetrics();
}
